import videojs, { VideoJsPlayer } from 'video.js'
import '!style-loader!css-loader!video.js/dist/video-js.css'
import './style.css'

const player: VideoJsPlayer = videojs(
  'player', {
    // https://docs.videojs.com/tutorial-options.html
    controls: true,
    autoplay: true,
    preload: 'auto',
    // Layout options explained here:
    // https://docs.videojs.com/tutorial-layout.html
    fill: true,
    responsive: true,
  }
)

player.src({
  src: 'https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8',
  // src: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
  // src: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8',
  type: 'application/x-mpegURL',
})

player.ready(() => {
  console.log('ready')
})

// App
//  - `id` URL arg
//  - Poster image
//  - `src` URL arg
//  - Events for analytics (only for Serato vids)
//     - `timeupdate` event (can't find in docs)

// CSP considerations
// - Nonce? https://content-security-policy.com/nonce/
// - Hash? https://content-security-policy.com/hash/
// - Either would need Lambda@Edge
// - Make a .txt file with all CSP headers and use those in edge function?
//    - File would be dynamically generated by build process and produce hash values for css and js files

// `embed.html` test page
// - Show production embed snippet using const playerProductionDomain
// - Add snippet to clipboard